[package]
name = "ghosthub-app"
build = "build.rs"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
name = "app"
path = "src/lib.rs"

[[bin]]
name = "ghosthub"
path = "src/main.rs"

[dependencies]
ghosthub-config.workspace = true
ghosthub-host.workspace = true
ghosthub-model.workspace = true
ghosthub-ui.workspace = true
ghosthub-workspace.workspace = true

[build-dependencies]
hex.workspace = true
sha2.workspace = true

[lints]
workspace = true
